sesiunea14/pet_adoption_agency/pet_adoption_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("pets/", include("pets.urls"))
]

sesiunea14/pet_adoption_agency/pets/urls.py
from django.urls import path
from . import views
app_name = "pets"
# urlpatterns = [
#     path("", views.pets, name="all_pets"),
#     path("<int:pet_id>/", views.pet_details, name="pet_details"),
#     path("pet/", views.pet_add, name="add")
# ]

#for VERSION 02
urlpatterns = [
    path("", views.PetsView.as_view(), name="all_pets"),
    path("<int:pk>/", views.PetDetailView.as_view(), name="pet_details"),
    path("pet/", views.PetCreateView.as_view(), name="add")
]

sesiunea14/pet_adoption_agency/pets/models.py
from django.db import models

PET_GENDERS = [
    ("F", "Female"),
    ("M", "Male")
]
PET_TYPES = [
    ("cat", "Cat"),
    ("dog", "Dog"),
    ("rabbit", "Rabbit")
]


# Create your models here.
class Pet(models.Model):
    name = models.CharField(max_length=50)
    location = models.CharField(max_length=30)
    gender = models.CharField(max_length=1, choices=PET_GENDERS, null=False)
    species = models.CharField(max_length=6, choices=PET_TYPES)

    def __str__(self):
        return f"{self.name} -> {self.location} -> {self.gender} -> {self.species}"

sesiunea14/pet_adoption_agency/pets/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse, reverse_lazy

from .models import Pet

# Create your views here.
def index(request):
    return HttpResponse('Hello World! Here is the  pet index.')


def pets(request):
    pets_list = Pet.objects.all()
    return render(request, "all_pets.html", {"pets": pets_list})


def pet_details(request, pet_id):
    pet = get_object_or_404(Pet, pk=pet_id)
    return render(request, "pet_details.html", {"pet": pet})


def pet_add(request):
    pet_data = request.POST.dict()
    try:
        pet = Pet(
            name=pet_data["name"],
            location=pet_data["location"],
            gender=pet_data["gender"],
            species=pet_data["species"]
        )
        pet.save()
    except KeyError:
        return render(request, "error.html", {"error_message": "Error! Invalid pet details!"})
    return HttpResponseRedirect(reverse("pets:all_pets"))


# VERSION 02 - IMPROVED
class PetsView(generic.ListView):
    template_name = "all_pets.html"
    context_object_name = "pets"

    def get_queryset(self):
        return Pet.objects.all()


class PetDetailView(generic.DetailView):
    model = Pet
    template_name = "pet_details.html"


class PetCreateView(generic.CreateView):
    model = Pet
    fields = ["name", "location", "gender", "species"]
    success_url = reverse_lazy("pets:all_pets")

sesiunea14/pet_adoption_agency/pets/templates/add_pet_form.html
<form action="{% url 'pets:add' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <label for="name">
            Name:
        </label>
        <input type="text" name="name" id="name">
        <br>
         <label for="location">
            Location:
        </label>
        <input type="text" name="location" id="location">
        <br>
        <label for="gender">
            Gender:
        </label>
        <label for="gender(F)">
            Female
        </label>
        <input type="radio" name="gender" id="gender(F)" value="F">
        <label for="gender(M)">
            Male
        </label>
        <input type="radio" name="gender" id="gender(M)" value="M">
        <br>
        <label for="species">
            Specie:
        </label>
        <input type="text" name="species" id="species">
    </fieldset>
    <input type="submit" value="ADD">
</form>

sesiunea14/pet_adoption_agency/pets/templates/all_pets.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pets</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% if pets %}
    <h2>
        Pets up for adoption
    </h2>
    <div class="pets-list">
         <ul>
            {% for pet in pets %}
                <li>
                    <a href="{% url 'pets:pet_details' pet.id %}">{{pet}}</a>
                </li>
            {% endfor %}
        </ul>
    </div>


{% endif %}
{% include "add_pet_form.html" %}
</body>
</html>

sesiunea14/pet_adoption_agency/pets/templates/error.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error</title>
</head>
<body>
{{error_message}}
</body>
</html>

sesiunea14/pet_adoption_agency/pets/templates/pet_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ pet.name }}</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
          crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="{% static 'detail.css' %}">
</head>
<body>
<div class="pet-details">
    <span class="pet-species">
    {% if pet.species == 'cat' %}
        <i class='fas fa-cat'></i>
    {% elif pet.species == 'dog' %}
        <i class='fas fa-dog'></i>
    {% elif pet.species == 'rabbit' %}
        <i class='fa fa-circle'></i>
    {% endif %}
    </span>
    <span class="pet-name">{{ pet.name }}</span>
    <span class="pet-location"><i class='fa-solid fa-map-location '></i>{{ pet.location }}</span>
    <span class="pet-gender">
    {% if pet.gender == "F" %}
        <i class='fa fa-female'></i>
    {% else %}
        <i class='fa fa-male'></i>
    {% endif %}
    </span>

</div>
</body>
</html>